[package]
name = "embedded_lmdb"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "tuplespaceInstanton/protobuf-codec",
  "txn_types/protobuf-codec",
  "violetabft/protobuf-codec",
  "ekvproto/protobuf-codec",
]
prost-codec = [
  "tuplespaceInstanton/prost-codec",
  "txn_types/prost-codec",
  "violetabft/prost-codec",
  "ekvproto/prost-codec",
]
jemalloc = ["lmdb/jemalloc"]
porBlock = ["lmdb/porBlock"]
sse = ["lmdb/sse"]

[dependencies]
encryption = { path = "../encryption" }
edb = { path = "../edb" }
hex = "0.4"
tuplespaceInstanton = { path = "../tuplespaceInstanton" }
num_cpus = "1"
prometheus = { version = "0.8", features = ["nightly", "push"] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
edb_alloc = { path = "../edb_alloc" }
violetabftstore::interlock:: = { path = "../violetabftstore::interlock::" }
txn_types = { path = "../txn_types"}
lazy_static = "1.4.0"
time = "0.1"
configuration = { path = "../configuration" }
tempfile = "3.0"
serde = "1.0"
serde_derive = "1.0"
coarsetime = "0.1"
ekvproto = { git = "https://github.com/whtcorpsinc/ekvproto.git", default-features = false }
violetabft = { version = "0.6.0-alpha", default-features = false }
protobuf = "2"

[dependencies.lmdb]
git = "https://github.com/edb/rust-lmdb.git"
package = "lmdb"
features = ["encryption", "static_libcpp"]

[dependencies.prometheus-static-metric]
git = "https://github.com/whtcorpsinc/edb/rust-prometheus.git"
rev = ""

[dev-dependencies]
ekvproto = { git = "https://github.com/whtcorpsinc/ekvproto.git", default-features = false }
rand = "0.7"
toml = "0.4"
